name: Ruff Lint Check

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: チェックアウト
        uses: actions/checkout@v3

      - name: Python をセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: '3.8.10'

      - name: 依存パッケージのインストール
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Ruff チェック実行
        run: |
          ruff check ./backend
